PlayerAction = {}

require("lib/player_actions/skills/PlayerActionFullyLoaded")
require("lib/player_actions/skills/PlayerActionShockAndAwe")
require("lib/player_actions/skills/PlayerActionEscapeTase")
require("lib/player_actions/skills/PlayerActionUnseenStrike")
require("lib/player_actions/skills/PlayerActionDireNeed")
require("lib/player_actions/skills/PlayerActionExpertHandling")
require("lib/player_actions/skills/PlayerActionBloodthirstBase")
require("lib/player_actions/skills/PlayerActionAmmoEfficiency")
require("lib/player_actions/skills/PlayerActionMessiahGetUp")
require("lib/player_actions/skills/PlayerActionTaserMalfunction")
require("lib/player_actions/skills/PlayerActionTriggerHappy")
require("lib/player_actions/skills/PlayerActionStockholmSyndromeTrade")
require("lib/player_actions/skills/PlayerActionTagTeam")
require("lib/player_actions/skills/PlayerActionDamageControl")
